deploy:
  provider: NuGet
  api_key:
    secure: Ie7C0UoQ6Q18B9cyczb70wRyrimai7EZZefPV7SVRbU0wTnozUd3yQ+N6NmzCPTu
  artifact: /.*\.nupkg/
  
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
  
build:
  project: build.proj
  
artifacts:
  - path: '*.nupkg'
  
notifications:
  - provider: Email
    to:
      - daniel@cazzulino.com
    subject: '[kzu/oss] Building {{buildVersion}}'
    message: "{{status}} - {{message}} ({{commitId}})"
    on_build_status_changed: true    
    on_build_success: true
    on_build_failure: true
