name: ⚙ dotnet
description: Configures dotnet if the repo/org defines the DOTNET custom property

runs:
  using: composite
  steps:
    - name: 🔎 dotnet
      id: dotnet
      shell: bash
      run: |
        VERSIONS=$(gh api /repos/${{ github.repository }}/properties/values | jq -r '.[] | select(.property_name == "DOTNET") | .value')
        echo "versions=$VERSIONS" >> $GITHUB_OUTPUT        

    - name: ⚙ dotnet
      if: steps.dotnet.outputs.versions != ''
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ steps.dotnet.outputs.versions }}
