name: +M▼ includes
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.md'    
      - '!changelog.md'

jobs:
  includes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖 defaults
        uses: devlooped/actions-bot@v1
        with:
          name: ${{ secrets.BOT_NAME }}
          email: ${{ secrets.BOT_EMAIL }}
          gh_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🤘 checkout
        uses: actions/checkout@v4
        with: 
          token: ${{ env.GH_TOKEN }}

      - name: +M▼ includes
        uses: devlooped/actions-include@v4

      - name: ✍ commit
        run: |
          git config --local user.name ${{ env.BOT_AUTHOR }}
          git config --local user.email ${{ env.BOT_EMAIL }}
          git add .
          git commit -m "+M▼ includes" || exit 0
          git push
